---
title: "Gender GLEE Data Request"
author: "Ryan Thomas"
date: "2023-09-22"
output: html_document
---

The data for this request can be downloaded from google drive Then upload the data using the web interface. Click the folcer icon, and then the file upload icon. Then select the file downladed from the link above.

```{r}
library(googlesheets4)
library(tidyverse)
library(disR)
```



```{r}
# Download data from:
# https://docs.google.com/spreadsheets/d/1I5TDMy7dyBHjTZ5D8K7I_MtPfFG4qPI7o084fBhAtMo/edit#gid=0
load("../../data/extract.Rdata")

gender_finance <- filter_indicators(ind_code = "EG.3.2-27", dn = "Sex") %>% 
   
 join_tables()  %>% 

 mutate(unit = if_else(substr(udn, 5, 5) == "2", "Number"
                , if_else(substr(udn, 5, 5) == "1", "Value","PROCESS"))) %>%
  
  select(ic, ro, ou, a_code, a_name, unit, Disaggregate.Name, Disaggregate.Country, 
         year, actual, target) %>%
  
 
  pivot_wider(names_from = "unit", values_from = c("actual", "target")
              , values_fn = ~if(all(is.na(.))) NA_real_ else sum(., na.rm=T)) %>%
  filter(if_all(ends_with("Value|Number"), ~ . > 0)) %>%
  mutate(per_person_actual = actual_Value / actual_Number
         , per_person_target = target_Value, target_Number) %>%
  pivot_wider(id_cols = c(ic, ro, ou, a_code, a_name, year)
              , names_from = Disaggregate.Name
              , values_from = c(per_person_actual, per_person_target)
              , values_fn = ~ sum_(.)) %>%
  filter(ro == "USAID"  & between(year, left = 2020, right = 2025)) %>% arrange(year) %>%
  mutate(`Actual_Financing Ratio (Female/Male)` = per_person_actual_Female/per_person_actual_Male
         , `Target_Financing Ratio (Female/Male)` = per_person_target_Female/per_person_target_Male
         , year = paste0("FY", year)) %>%
  pivot_longer(cols = c(`Actual_Financing Ratio (Female/Male)`, `Target_Financing Ratio (Female/Male)`)
               , names_to = "disaggregate"
               , values_to = "value") %>% 
  select(ic, ro, ou, a_code, a_name, disaggregate, year, value) %>%
  separate(disaggregate, into = c("type", "disaggregate"), sep = "_") %>%
  pivot_wider(id_cols = c(ic, ro, ou, a_code, a_name, disaggregate) 
              , names_from = c(year, type), values_from = value, names_sep = " ") %>%
  mutate(ou = gsub(r"{\s*\([^\)]+\)}","",as.character(ou))
         , a_code = as.character(a_code))
```


```{r include = F}
indicators %>%
  filter(ic == "EG.3-2") %>%
  left_join(values, join_by(id == id_ind)) %>%
  filter(year > 2022 & !is.na(target))
```


```{r}
load("../../data/basic.Rdata")
```


```{r}
glee <- function(x) {
  x %>%
  # Join the values and IM info 
  left_join(x = ., y = values # join values
                , by = join_by(id == id_ind)
                , suffix = c("_ind", "_val") # label variables 
                , keep = FALSE)  %>% #distinct(year)
  left_join(x = ., y = ims # join implementing mechanisms
                , join_by(id_im == id))  %>%
  filter(year %in% paste0("FY", 2020:2025) & ro == "USAID") %>%  # filter only the relevant years
  arrange(year, desc(type)) %>%
  # create a wide data set with a column for each disaggregate
  pivot_wider(id_cols = c(ic, ro, ou, a_code, a_name, disaggregate)
               , names_from = c(year, type)
               , names_sep = " "
               , values_from = value)
  }
```


```{r}
indicators %>% filter(ic == "EG.3-2")  %>% 
  left_join(x = ., y = values # join values
                , by = join_by(id == id_ind)
                , suffix = c("_ind", "_val") # label variables 
                , keep = FALSE)  %>% #distinct(year)
  left_join(x = ., y = ims # join implementing mechanisms
                , join_by(id_im == id)) %>% 
  filter(year == "FY2022")
```


```{r}
water <- readxl::read_excel("C:/Users/rythomas/Downloads/GLEE Data.xlsx"
                   , sheet = "PPR Indicators Multiple Years"
                   , skip = 15) %>%
  left_join(readxl::read_excel("C:/Users/rythomas/Downloads/GLEE Data.xlsx"
                   , sheet = "Targets for FY23, FY24, FY25"
                   , skip = 4)) %>%
  select(-c(`...4`, `...5`, `Baseline Date`, `Baseline Value`
            , `PPR Indicator Metric`)) %>%
  mutate(ro = "USAID")

```

```{r}
# Link to google sheets for climate indicators
# These were sent to Ryan from Bryce, and then manually edited to select only
# the relevant columns and rename columns in line with other indicators in 
# this request.
s1 <- "https://docs.google.com/spreadsheets/d/1gPy3cPDu2sqix81yw55WH8IYhMYSY9lOXW9Ad2DSdnY/edit#gid=729767621"
s2 <- "https://docs.google.com/spreadsheets/d/1iky0LwRXry_FZ21Oy2Y7w90xSKk5KmhNJm4tKqouF0w/edit#gid=1694621469"

climate <- googlesheets4::read_sheet(s1, skip = 7) %>%
  left_join( googlesheets4::read_sheet(s2, skip = 9)) %>%
  mutate(across(starts_with("FY"), ~ as.numeric(.))
                , ro = "USAID")
```



```{r}

all_data <- bind_rows({
  # eg.3_2 
  indicators %>% filter(ic == "EG.3-2") %>%
  unite(d1, d2, col="disaggregate", sep = " > ") %>%
  glee() 
  
} ,{
  # eg.3.2_24
  indicators %>% filter(ic == "EG.3.2-24" & d2 == "Sex") %>%
  unite(d1, d2, d3, col="disaggregate", sep = " > ") %>%
  glee()
  
}, { 
  # eg.3.2_25
  indicators %>% filter(ic == "EG.3.2-25" & d2 == "Sex") %>%
  unite(d1, d2, d3, col="disaggregate", sep = " > ") %>%
  glee()
  
}, {
  # eg.3.2_26
  indicators %>% filter(ic == "EG.3.2-26" & d3 == "Sex") %>%
  unite(d1, d2, d3, d4, col = "disaggregate", sep = " > ") %>%
  glee()
  
} ,{
  # eg.3.2_27
  indicators %>% filter(ic == "EG.3.2-27" & d3 == "Sex of recipient(s)") %>%
  unite(d1, d2, d3, d4, col = "disaggregate", sep = " > ") %>%
  glee()
  
} ,{
  # eg.3.3_10
  indicators  %>% filter(ic == "EG.3.3-10") %>%
  unite(d1, d2, col = "disaggregate", sep = " > ") %>%
  glee()

} ,{
  #eg.4.2_7
  indicators %>% filter(ic == "EG.4.2-7" & d1 == "Sex of participant (no double-counting)") %>%
  unite(d1, d2, col = "disaggregate", sep = " > ") %>%
  glee()
  
} , {
  indicators %>% filter(ic == "EG.10.4-7" & d2 == "Sex") %>%
  unite(d1, d2, d3, col = "disaggregate", sep = " > ") %>%
  glee()
  
}, {
  indicators %>% filter(ic == "EG.10.4-8" & d2 == "Sex") %>%
  unite(d1, d2, d3, col = "disaggregate", sep = " > ") %>%
  glee()
  
} , {
  indicators %>% filter(ic == "EG.3.2-2" & d1 == "Sex") %>%
  unite(d1, d2, col = "disaggregate", sep = " > ") %>%
  glee()
  
} , {# ES.5-1
  indicators %>% filter(ic == "ES.5-1" & d1 == "Sex") %>%
  unite(d1, d2, col = "disaggregate", sep = " > ") %>%
  glee()
  
} ,{
  indicators %>% filter(ic == "GNDR-2") %>%
  unite(d1, col = "disaggregate", sep = " > ") %>%
  glee()
  
}, {
  indicators %>% filter(ic == "YOUTH-3") %>%
  unite(d1, col = "disaggregate", sep = " > ") %>%
  glee()
  
}, {# hl.8.2_2
  indicators %>% filter(ic == "HL.8.2-2" & d1 == "Sex") %>%
  unite(d1, d2, col = "disaggregate", sep = " > ") %>%
  glee()
  
}, {
  gender_finance
  
} , {
  water

}, {
  climate
}) %>%
  arrange(ic, ro, ou, a_code, disaggregate)  %>%
    rename(`Indicator Code` = ic
           , `Activity Code` = a_code
           , `Activity Name` = a_name
           , Disaggregates = disaggregate) %>%
  select(-c(`FY2023 Actual`, `FY2024 Actual`, `FY2025 Actual`))
all_data[sapply(all_data, is.infinite)] <- NA
all_data <- all_data %>% nest(data = -c(ro, ou))
# all_data %>% filter(str_detect(`Activity Code` , "1287"))
```



```{r include = F}
glee_sheet <- "https://docs.google.com/spreadsheets/d/17eOM88pTy-UjV3S_1GK5Y15nmNfA39R29VUSc6Do5fA/edit#gid=424389374"

participants <- c("Bangladesh", "Burkina Faso"
                  , "Democratic Republic of the Congo", "Egypt", "Ethiopia" 
                  ,"Ghana", "Haiti", "Honduras", "Indonesia", "Kenya", "Liberia"
                  , "Madagascar", "Malawi", "Mali", "Mozambique", "Niger"
                  , "Nigeria", "Rwanda", "Senegal", "Somalia", "South Sudan",
                  "Sudan", "Tajikistan", "Tanzania", "Uganda", "Zambia", "Zimbabwe")


all_data %>% filter(str_detect(ou, "Sudan"))
all_data <- all_data %>% filter(ou %in% participants) %>% arrange(ou)

# map2(.x = all_data$ou
#      , .y = all_data$data
#      , .f = ~ sheet_write(.y, ss=glee_sheet, as.character(.x)), quitely= T)

```
