---
title: "Gender Gap analysis"
author: "Ryan Thomas"
date: "2023-09-05"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(disR)

load("../../../database/data/extract.Rdata")
# ppp <- read.csv("../../../database/data/API_PA.NUS.PPP_DS2_en_csv_v2_5734723.csv", skip = 4) %>%
#   select(-`Indicator.Name`,- `Indicator.Code`) %>%
#   pivot_longer(-c(`Country.Name`, `Country.Code`), 
#                names_to = "year", values_to = "ppp_multiplier") %>%
#   mutate(year = as.integer(str_remove(year, "X"))) %>%
#   filter(!is.na(ppp_multiplier))
```

## R Markdown

```{r}
ind_key <- "Sex"
ind_code = "EG.3.2-27"

filter_indicators(ind_code = ind_code, dn = ind_key)
```



```{r}
filter_indicators(ind_code = ind_code, dn = ind_key) %>%
  mutate(unit = if_else(substr(udn, 5, 5) == "2", "Number"
                , if_else(substr(udn, 5, 5) == "1", "Value","PROCESS"))) 
```



```{r}
#### Replicating from Extract Database
join_tables <- function(x) {
  x %>% #distinct(udn)

    # join values
    left_join(x = ., y = values
            , by = join_by(id == id_ind)
            , suffix = c("_ind", "_val") # label variables
            , keep = FALSE)  %>%
    
    # join activities details
    left_join(activities
              , by = join_by(id_ac == id)
              , suffix = c("_ind", "_val") # label variables
              , keep = FALSE)
  }
```


```{r}
dat <- filter_indicators(ind_code = ind_code, dn = ind_key) %>% 
   
  join_tables()  %>% 

 mutate(unit = if_else(substr(udn, 5, 5) == "2", "Number"
                , if_else(substr(udn, 5, 5) == "1", "Value","PROCESS"))) %>%
  
  select(ic, ro, ou, a_code, a_name, unit, Disaggregate.Name, Disaggregate.Country, 
         year, actual, target) %>%
  
 
  pivot_wider(names_from = "unit", values_from = c("actual", "target")
              , values_fn = ~if(all(is.na(.))) NA_real_ else sum(., na.rm=T)) %>%
  filter(if_all(ends_with("Value|Number"), ~ . > 0))
```


```{r}
load("../../../database/data/extract.Rdata")

gender_finance <- filter_indicators(ind_code = ind_code, dn = ind_key) %>% 
   
  join_tables()  %>% 

 mutate(unit = if_else(substr(udn, 5, 5) == "2", "Number"
                , if_else(substr(udn, 5, 5) == "1", "Value","PROCESS"))) %>%
  
  select(ic, ro, ou, a_code, a_name, unit, Disaggregate.Name, Disaggregate.Country, 
         year, actual, target) %>%
  
 
  pivot_wider(names_from = "unit", values_from = c("actual", "target")
              , values_fn = ~if(all(is.na(.))) NA_real_ else sum(., na.rm=T)) %>%
  filter(if_all(ends_with("Value|Number"), ~ . > 0)) %>%
  mutate(per_person_actual = actual_Value / actual_Number
         , per_person_target = target_Value, target_Number) %>%
  pivot_wider(id_cols = c(ic, ro, ou, a_code, a_name, year)
              , names_from = Disaggregate.Name
              , values_from = c(per_person_actual, per_person_target)
              , values_fn = ~ sum_(.)) %>%
  filter(ro == "USAID"  & between(year, left = 2020, right = 2025)) %>% arrange(year) %>%
  mutate(`Actual_Financing Ratio (Female/Male)` = per_person_actual_Female/per_person_actual_Male
         , `Target_Financing Ratio (Female/Male)` = per_person_target_Female/per_person_target_Male
         , year = paste0("FY", year)) %>%
  pivot_longer(cols = c(`Actual_Financing Ratio (Female/Male)`, `Target_Financing Ratio (Female/Male)`)
               , names_to = "disaggregate"
               , values_to = "value") %>% 
  select(ic, ro, ou, a_code, a_name, disaggregate, year, value) %>%
  separate(disaggregate, into = c("type", "disaggregate"), sep = "_") %>%
  pivot_wider(id_cols = c(ic, ro, ou, a_code, a_name, disaggregate) 
              , names_from = c(year, type), values_from = value, names_sep = " ") 
```




```{r}
"../output/gender_finance_gap_by_ac.xlsx"
write.xlsx(gender_finance_gap_by_ac, file="../output/gender_finance_gap_by_ac.xlsx")
write.xlsx(gender_finance_gap_by_ou,file="../output/gender_finance_gap_by_ou.xlsx")


```

