---
title: "PPP Analysis"
author: "Ryan Thomas"
date: "2023-09-08"
output:
  html_document:
    df_print: paged
---


Here is the Progress Snapshot view of Sales without accounting for PPP. These values are based on the reported dollars at the time of sale.
```{r echo=F, warning=F}
library(disR)
library(tidyverse)
ind_code <- "EG.3.2-26/EG.3.2-x19"
ind_key <- "Sex"
```


```{r echo=F}
bind_rows({
  indicators %>%  
  #Select all the indicators you want
  filter(str_detect(ic_1819, ind_code) &
           if_any(everything(), ~str_detect(., ind_key)) &
           if_any(d4, ~str_detect(., "Value of Sales"))) %>% 
  # sum_indicators(ind_code = ind_code, total = T, 
  #                disaggregate = c("Crop Land|Cultivated Pasture|Aquaculture"))
  left_join(x = ., y = filter(values, type=="Actual")
            , by = join_by(id == id_ind)
            , suffix = c("_ind", "_val") # label variables 
            , keep = FALSE)  %>% #distinct(year)
  
  group_by(year) %>%
  summarise(value = sum(value, na.rm=T)) %>%
  pivot_wider(names_from = c("year")
              , values_from = "value"
              , values_fn = ~ if(all(is.na(.))) NA_real_ else sum(., na.rm=T)) %>%
  relocate(all_of(paste0("FY", 2011:2022)), .after=everything()) %>%
  mutate(Label = "Value of annual sales of producers and firms receiving USG assistance", 
         .before=everything()) %>%
    mutate(`LOI Total` = rowSums(select(., starts_with("FY")), na.rm=T))
  }
  , {
    indicators %>%  
      #Select all the indicators you want
      filter(str_detect(ic_1819, ind_code) &
               if_any(everything(), ~str_detect(., ind_key)) &
               if_any(d4, ~str_detect(., "Value of Sales"))) %>% 
      # sum_indicators(ind_code = ind_code, total = T, 
      #                disaggregate = c("Crop Land|Cultivated Pasture|Aquaculture"))
      left_join(x = ., y = filter(values, type=="Actual")
                , by = join_by(id == id_ind)
                , suffix = c("_ind", "_val") # label variables 
                , keep = FALSE)  %>% #distinct(year)
      
      group_by(ic, year) %>%
      summarise(value = sum(value, na.rm=T)) %>%
      pivot_wider(names_from = c("year")
                  , values_from = "value"
                  , values_fn = ~ if(all(is.na(.))) NA_real_ else sum(., na.rm=T)) %>%
      relocate(all_of(paste0("FY", 2011:2022)), .after=everything()) %>%
      mutate(Label = "Value of annual sales of producers and firms receiving USG assistance", 
             .before=everything())
    }
  , {
    indicators %>%  
      #Select all the indicators you want
      filter(str_detect(ic_1819, ind_code) &
               if_any(everything(), ~str_detect(., ind_key)) &
               if_any(d4, ~str_detect(., "Value of Sales")) &
               if_any(d2,~str_detect(., "Producer - Smallholder"))) %>% 
      # sum_indicators(ind_code = ind_code, total = T, 
      #                disaggregate = c("Crop Land|Cultivated Pasture|Aquaculture"))
      left_join(x = ., y = filter(values, type=="Actual")
                , by = join_by(id == id_ind)
                , suffix = c("_ind", "_val") # label variables 
                , keep = FALSE)  %>% #distinct(year)
      
      group_by(year) %>%
      summarise(value = sum(value, na.rm=T)) %>%
      pivot_wider(names_from = c("year")
                  , values_from = "value"
                  , values_fn = ~ if(all(is.na(.))) NA_real_ else sum(., na.rm=T)) %>%
      relocate(all_of(paste0("FY", 2011:2022)), .after=everything()) %>%
      mutate(Label = "$ of which are from smallholder producers", 
             .before=everything()) %>%
    mutate(`LOI Total` = rowSums(select(., starts_with("FY")), na.rm=T))
  }
  , {
    indicators %>%  
      #Select all the indicators you want
      filter(str_detect(ic_1819, ind_code) &
               if_any(everything(), ~str_detect(., ind_key)) &
               if_any(d4, ~str_detect(., "Value of Sales")) &
               if_any(d2,~str_detect(., "Producer - Non-Smallholder"))) %>% 
      # sum_indicators(ind_code = ind_code, total = T, 
      #                disaggregate = c("Crop Land|Cultivated Pasture|Aquaculture"))
      left_join(x = ., y = filter(values, type=="Actual")
                , by = join_by(id == id_ind)
                , suffix = c("_ind", "_val") # label variables 
                , keep = FALSE)  %>% #distinct(year)
      
      group_by(year) %>%
      summarise(value = sum(value, na.rm=T)) %>%
      pivot_wider(names_from = c("year")
                  , values_from = "value"
                  , values_fn = ~ if(all(is.na(.))) NA_real_ else sum(., na.rm=T)) %>%
      relocate(all_of(paste0("FY", 2018:2022)), .after=everything()) %>%
      mutate(Label = "$ of which are from non-smallholder producers", 
             .before=everything()) %>%
    mutate(`LOI Total` = rowSums(select(., starts_with("FY")), na.rm=T))
  }
  ,{
    indicators %>%  
      #Select all the indicators you want
      filter(str_detect(ic_1819, ind_code) &
               if_any(everything(), ~str_detect(., ind_key)) &
               if_any(d4, ~str_detect(., "Value of Sales")) &
               if_any(d2,~str_detect(., "Firm"))) %>% 
      # sum_indicators(ind_code = ind_code, total = T, 
      #                disaggregate = c("Crop Land|Cultivated Pasture|Aquaculture"))
      left_join(x = ., y = filter(values, type=="Actual")
                , by = join_by(id == id_ind)
                , suffix = c("_ind", "_val") # label variables 
                , keep = FALSE)  %>% #distinct(year)
      
      group_by(year) %>%
      summarise(value = sum(value, na.rm=T)) %>%
      pivot_wider(names_from = c("year")
                  , values_from = "value"
                  , values_fn = ~ if(all(is.na(.))) NA_real_ else sum(., na.rm=T)) %>%
      relocate(all_of(paste0("FY", 2018:2022)), .after=everything()) %>%
      mutate(Label = "$ of which are from firms", 
             .before=everything()) %>%
    mutate(`LOI Total` = rowSums(select(., starts_with("FY")), na.rm=T))
  }) %>%
  relocate(`Indicator Code`=ic, .after=Label)
```


Below I account for the PPP based on the World Bank's PPP multiplier.
```{r}
ppp <- read.csv("../API_PA.NUS.PPP_DS2_en_csv_v2_5734723.csv", skip = 4) %>%
  select(-`Indicator.Name`,- `Indicator.Code`) %>%
  pivot_longer(-c(`Country.Name`, `Country.Code`), 
               names_to = "year", values_to = "ppp_multiplier") %>%
  mutate(year = as.integer(str_remove(year, "X"))) %>%
  filter(!is.na(ppp_multiplier))
ppp
```


```{r}
indicators %>%  
  #Select all the indicators you want
  filter(str_detect(ic_1819, ind_code) &
           if_any(everything(), ~str_detect(., ind_key)) &
           if_any(d4, ~str_detect(., "Value of Sales"))) %>% 
  # sum_indicators(ind_code = ind_code, total = T, 
  #                disaggregate = c("Crop Land|Cultivated Pasture|Aquaculture"))
  left_join(x = ., y = filter(values, type=="Actual")
            , by = join_by(id == id_ind)
            , suffix = c("_ind", "_val") # label variables 
            , keep = FALSE) %>%
  left_join(x = ., y =ims) %>%
  mutate(year = as.integer(str_remove(year, "FY"))) %>%
  left_join(ppp, join_by(year, ou == Country.Name)) %>%
  mutate(ppp_value = value * ppp_multiplier) %>%
  
  group_by(year) %>%
  summarise(value = sum(ppp_value, na.rm=T)) %>%
  pivot_wider(names_from = c("year")
              , values_from = "value"
              , values_fn = ~ if(all(is.na(.))) NA_real_ else sum(., na.rm=T)) %>%
  relocate(all_of(paste0(2011:2022)), .after=everything()) %>%
  mutate(Label = "Value of annual sales of producers and firms receiving USG assistance", 
         .before=everything()) %>%
  mutate(`LOI Total` = rowSums(select(., starts_with("2")), na.rm=T))
```



```{r}
ind_code <- "EG.3.2-26/EG.3.2-x19"
ind_key <- "Sex"
bind_rows({
  indicators %>%  
  #Select all the indicators you want
  filter(str_detect(ic_1819, ind_code) &
           if_any(everything(), ~str_detect(., ind_key)) &
           if_any(d4, ~str_detect(., "Value of Sales"))) %>% 
  # sum_indicators(ind_code = ind_code, total = T, 
  #                disaggregate = c("Crop Land|Cultivated Pasture|Aquaculture"))
  left_join(x = ., y = filter(values, type=="Actual")
            , by = join_by(id == id_ind)
            , suffix = c("_ind", "_val") # label variables 
            , keep = FALSE)  %>% #distinct(year)
  
  group_by(year) %>%
  summarise(value = sum(value, na.rm=T)) %>%
  pivot_wider(names_from = c("year")
              , values_from = "value"
              , values_fn = ~ if(all(is.na(.))) NA_real_ else sum(., na.rm=T)) %>%
  relocate(all_of(paste0("FY", 2011:2022)), .after=everything()) %>%
  mutate(Label = "Value of annual sales of producers and firms receiving USG assistance", 
         .before=everything()) %>%
    mutate(`LOI Total` = rowSums(select(., starts_with("FY")), na.rm=T))
  }
  , {
    indicators %>%  
      #Select all the indicators you want
      filter(str_detect(ic_1819, ind_code) &
               if_any(everything(), ~str_detect(., ind_key)) &
               if_any(d4, ~str_detect(., "Value of Sales"))) %>% 
      # sum_indicators(ind_code = ind_code, total = T, 
      #                disaggregate = c("Crop Land|Cultivated Pasture|Aquaculture"))
      left_join(x = ., y = filter(values, type=="Actual")
                , by = join_by(id == id_ind)
                , suffix = c("_ind", "_val") # label variables 
                , keep = FALSE)  %>% #distinct(year)
      
      group_by(ic, year) %>%
      summarise(value = sum(value, na.rm=T)) %>%
      pivot_wider(names_from = c("year")
                  , values_from = "value"
                  , values_fn = ~ if(all(is.na(.))) NA_real_ else sum(., na.rm=T)) %>%
      relocate(all_of(paste0("FY", 2011:2022)), .after=everything()) %>%
      mutate(Label = "Value of annual sales of producers and firms receiving USG assistance", 
             .before=everything())
    }
  , {
    indicators %>%  
      #Select all the indicators you want
      filter(str_detect(ic_1819, ind_code) &
               if_any(everything(), ~str_detect(., ind_key)) &
               if_any(d4, ~str_detect(., "Value of Sales")) &
               if_any(d2,~str_detect(., "Producer - Smallholder"))) %>% 
      # sum_indicators(ind_code = ind_code, total = T, 
      #                disaggregate = c("Crop Land|Cultivated Pasture|Aquaculture"))
      left_join(x = ., y = filter(values, type=="Actual")
                , by = join_by(id == id_ind)
                , suffix = c("_ind", "_val") # label variables 
                , keep = FALSE)  %>% #distinct(year)
      
      group_by(year) %>%
      summarise(value = sum(value, na.rm=T)) %>%
      pivot_wider(names_from = c("year")
                  , values_from = "value"
                  , values_fn = ~ if(all(is.na(.))) NA_real_ else sum(., na.rm=T)) %>%
      relocate(all_of(paste0("FY", 2011:2022)), .after=everything()) %>%
      mutate(Label = "$ of which are from smallholder producers", 
             .before=everything()) %>%
    mutate(`LOI Total` = rowSums(select(., starts_with("FY")), na.rm=T))
  }
  , {
    indicators %>%  
      #Select all the indicators you want
      filter(str_detect(ic_1819, ind_code) &
               if_any(everything(), ~str_detect(., ind_key)) &
               if_any(d4, ~str_detect(., "Value of Sales")) &
               if_any(d2,~str_detect(., "Producer - Non-Smallholder"))) %>% 
      # sum_indicators(ind_code = ind_code, total = T, 
      #                disaggregate = c("Crop Land|Cultivated Pasture|Aquaculture"))
      left_join(x = ., y = filter(values, type=="Actual")
                , by = join_by(id == id_ind)
                , suffix = c("_ind", "_val") # label variables 
                , keep = FALSE)  %>% #distinct(year)
      
      group_by(year) %>%
      summarise(value = sum(value, na.rm=T)) %>%
      pivot_wider(names_from = c("year")
                  , values_from = "value"
                  , values_fn = ~ if(all(is.na(.))) NA_real_ else sum(., na.rm=T)) %>%
      relocate(all_of(paste0("FY", 2018:2022)), .after=everything()) %>%
      mutate(Label = "$ of which are from non-smallholder producers", 
             .before=everything()) %>%
    mutate(`LOI Total` = rowSums(select(., starts_with("FY")), na.rm=T))
  }
  ,{
    indicators %>%  
      #Select all the indicators you want
      filter(str_detect(ic_1819, ind_code) &
               if_any(everything(), ~str_detect(., ind_key)) &
               if_any(d4, ~str_detect(., "Value of Sales")) &
               if_any(d2,~str_detect(., "Firm"))) %>% 
      # sum_indicators(ind_code = ind_code, total = T, 
      #                disaggregate = c("Crop Land|Cultivated Pasture|Aquaculture"))
      left_join(x = ., y = filter(values, type=="Actual")
                , by = join_by(id == id_ind)
                , suffix = c("_ind", "_val") # label variables 
                , keep = FALSE)  %>% #distinct(year)
      
      group_by(year) %>%
      summarise(value = sum(value, na.rm=T)) %>%
      pivot_wider(names_from = c("year")
                  , values_from = "value"
                  , values_fn = ~ if(all(is.na(.))) NA_real_ else sum(., na.rm=T)) %>%
      relocate(all_of(paste0("FY", 2018:2022)), .after=everything()) %>%
      mutate(Label = "$ of which are from firms", 
             .before=everything()) %>%
    mutate(`LOI Total` = rowSums(select(., starts_with("FY")), na.rm=T))
  }) %>%
  relocate(`Indicator Code`=ic, .after=Label)
```

