---
title: "Reporting Organizations Data Request"
author: "Ryan Thomas"
date: "2023-12-04"
output: html_document
---

The data for this request can be downloaded from google drive Then upload the data using the web interface. Click the folder icon, and then the file upload icon. Then select the file downladed from the link above.

```{r}
library(googlesheets4)
library(tidyverse)
library(disR)
library(openxlsx)
```



```{r}
# change this to be the location of the files
input_dir <- "../../../indicators/basic/" 

pattern <- "_20230622.xlsx"
indicator_files <- list.files(input_dir, pattern = "20230622", full.names = T)

sheet_names <- c("RO Total", "RO Full Disaggs", "OU Total", "OU Full Disaggs"
                 ,"IM Total", "IM Full Disaggs")

sheets <- expand.grid(path = indicator_files
                      , name = sheet_names
                      , stringsAsFactors = F)

read.interagency <- function(x, y) {
  if(y %in% getSheetNames(x)) {
    read.xlsx(x, sheet = y, fillMergedCells=T) %>%
      mutate(sheet = y, .before=everything())
  }
}

all_data <- purrr::map2(sheets$path, sheets$name, 
                         ~ read.interagency(.x, .y), .progress = T)  %>%
  
  purrr::list_rbind() %>%
  
  select(sheet, RO, Indicator.Code, OU, Pa.Id, Activity.Name
         , `Indicator.Disaggregates:.1st.Order`, `Indicator.Disaggregates:.2nd.Order`
         , `Indicator.Disaggregates:.3rd.Order`, `Indicator.Disaggregates:.4th.Order`
         , ends_with(as.character(2020:2025)))
```



```{r}
dat <- all_data %>% 
  nest(data = -c(sheet, RO)) %>% 
  mutate(data = map(data, ~ select(., where(function(x) !all(is.na(x))))))

dat$data[2]
```



```{r include = F}

ro_sheet_ids <- data.frame(
  RO = c("USDA", "USADF", "Peace Corps", "MCC", "IFAD", "IAF", "GAFSP"),
  sheet_id = c("1V6d2xgU1b0lGVywWl5f_xuGWSoUgUZ1ZhTVnKevTD3s", 
  "1bJ9Qqls42aTq_NHxOjXq0aW4vSSlSodfGE50x2nwXF8", 
  "1444PKLq1lbZoOduHU0firf9xEurUecOACukTgMvH0MA", 
  "1JQCzvTZeouxZT7lpUQnRLwyXukkkSpxpRlUVJrP_9LU", 
  "17YtNFtt-neCh3otSQxeROoPBeHEBV-mhF3Cd-1qJLi4", 
  "11o6QnNAw8Zl94PqQ3vRirxegFlm-WngtBSsHabpnopM", 
  "1Ebyor7krp29EfSpeD0zFE_gfLxdAsLNK5FV0xffyJqw")
)

dat <- dat %>% 
  left_join(ro_sheet_ids) %>% 
  filter(!if_any(everything(), ~ is.na(.)))

#sheet_write(dat$data, ss = dat$sheet_id, sheet = dat$sheet)

list(data = dat$data, ss = dat$sheet_id, sheet = dat$sheet) %>%
  
       pmap(sheet_write)

```
