---
title: "UKSupp Indicators"
author: "Ryan Thomas"
date: "2023-09-18"
output: html_document
---

```{r setup, include=FALSE}
library(googlesheets4)
library(tidyverse)


```



```{r}
# data <- read.csv("../../../Downloads/UkrSupp2_FY23_TrackerToEndAllTrackers - Activity tracker with data (1).csv")

data <- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/1fmAibL9SUw04v3ce8FuQUkex4pKeSqVbP82j5oGe-6w/edit#gid=1689707295", 
                                  sheet = "final_activities", col_type = "c"
                                  , range = "final_activities!A1:DV144")
data <- data[,c(1,6, 7, 57:69)] 
totals <- data %>% 
  mutate(across((starts_with("E") | starts_with("HL")), ~ parse_number(.))) %>%
  mutate(OU = case_when(OU == "As a PIO, the Mission has requested data but not sure if it will be shared/reported. There should be Q3 data but this activity is not yet in DIS. I have offered to create the activity and input data since the MEL POC is OOO all August but TBD." ~  "Malawi"
                        , OU != "As a PIO, the Mission has requested data but not sure if it will be shared/reported. There should be Q3 data but this activity is not yet in DIS. I have offered to create the activity and input data since the MEL POC is OOO all August but TBD." ~ OU)) %>%
  group_by(OU) %>%
  summarise(across((starts_with("E") | starts_with("HL")), ~ sum_(.)))

write.csv(totals, "../output/UkSupp Q3 Indicator Totals.csv", na = "")
```


```{r}
totals %>% summarise(across(-OU, ~ sum_(.)))
```

