---
title: "Make Indicator Database from Extract"
author: "Ryan Thomas"
date: "2023-08-04"
output: html_document
---
```{r echo=F, warning=F, message=F}
options(scipen=999)
library(tidyverse)
library(openxlsx)

return_id <- function(row) {
  l <- round(log10(nrow(row))+1,0)
  id <- str_pad(rownames(row), width = l, pad = "0", side = "left")
  return(id)
}

# load("../database/extract/indicators_db.Rdata")

```



```{r}
dat <- read.csv("../indicators/DIS ENT - OU Activity Indicator Results (All Data)_20230622 Extract_Extract.csv")
dat <- dat %>%
  rename(ro = Reporting.Organization
         , ou = Operating.Unit
         , a_code = Activity.Code
         , a_name = Activity.Name
         , ic=Indicator.Code
         , ip = Activity.Vendor
         , a_end = Activity.End.Date
         , a_start = Activity.Start.Date
         , i_end = Indicator.End.Date
         , i_start = Indicator.Start.Date
         , d_end = Disaggregate.End.Date
         , d_start = Disaggregate.Start.Date
         , a_office = Activity.Office
         , status = Activity.Status
         , tags = Activity.Tags
         , id = ID.Managing.Office
         , m_code = Managing.Office.Code
         , m_office = Managing.Office.Name
         #, country = Disaggregate.Country
         , udn = UDN
         , year = Fiscal.Year
         , target = Target.Value
         , actual = Actual.Value)  %>%
  select(-id) %>%
  mutate(system = "dis") %>%
  mutate(Disaggregate.Country = if_else(Disaggregate.Country == "MALI"
                                        , "Mali", Disaggregate.Country)) %>%
  mutate(across(c(actual, target), ~ as.numeric(.)))
  
# read.ftfms <- function(x) {
#   out <- read.xlsx(x) %>%
#     separate_wider_delim(IndicatorName, ":", 
#                          names = c("IndicatorName", "Indicator.Code")) %>%
#     rename(Indicator.Name = IndicatorName
#          , Reporting.Organization = ReportingOrganization
#          , Managing.Office.Name = `Bureau/Region`
#          , Operating.Unit = OperatingUnit
#          , Activity.Code = `PA-ID`
#         
#          	, d1 = DisaggregationName1
#          	, d2 = DisaggregationName2
#          	, d3 = DisaggregationName3
#          	, d4 = DisaggregationName4
#          	, d5 = DisaggregationName5
# 
#          , Target.Value = TargetValue	
#          , Actual.Value = ActualValue
#          , Deviation.Narrative = DeviationNarrative	) %>%
#     mutate(across(starts_with("d"), ~ as.character(.))) %>%
#     mutate(system = "ftfms")
#   return(out)
# }

# files <- c("../indicators/FTFMS Full Dataset 2011-2019 1.xlsx",
#            "../indicators/FTFMS Full Dataset 2011-2019 2.xlsx")
# 
# ftfms <- map(files, read.ftfms) %>%
#  list_rbind()

```



# Indicators lookup
```{r}
disaggregate_countries <- dat %>% #select(-Disaggregate.Commodity) %>%
  distinct(ic, a_code, udn, Disaggregate.Country) %>%
  mutate(id = return_id(.), .before = everything()) %>%
  arrange(a_code)

# Indicators
indicators <- dat %>% #select(-Disaggregate.Commodity) %>%
  distinct(ic, udn, d_end, d_start
           , across(starts_with("Disaggregate")), Indicator.Origin, Indicator.Tags
           , Is.FTF, Is.PPR, Is.PMP, Is.Neither.PPR.PMP, Is.COVID
           , Indicator.Collection.Frequency, i_end) %>% 
  mutate(uudn = paste(ic, udn, sep="_")
    , id = return_id(.), .before = everything())

```

## Get UDN formulas from DIS (Paul)
```{r}
library(googlesheets4)
url <- "https://docs.google.com/spreadsheets/d/14iw2PRItDeB-OY8deb5klnN9HwbnhiAWv7DiTS5EwVo/edit#gid=1094963191"
udns <- read_sheet(url,  sheet = "FTF 20230915")  %>% 
  
  mutate(across(is.list, .fn = ~ as.character(unlist(.)))) %>%
  rename_with(.cols = everything(.), .fn = ~ stringr::str_replace_all(., " ", ".")) %>%
  rename(#ro = Reporting.Organization
         #, ou = Operating.Unit
         #, a_code = Activity.Code
         #, a_name = Activity.Name
         , ic=Indicator.Code
         #, ip = Activity.Vendor
         #, a_end = Activity.End.Date
         #, a_start = Activity.Start.Date
         #, i_end = Indicator.End.Date
         #, i_start = Indicator.Start.Date
         , d_end = Disaggregate.End.Date
         , d_start = Disaggregate.Start.Date
         #, a_office = Activity.Office
         #, status = Activity.Status
         #, tags = Activity.Tags
         #, id = ID.Managing.Office
         #, m_code = Managing.Office.Code
         #, m_office = Managing.Office.Name
         #, country = Disaggregate.Country
         , udn = UDN
         #, year = Fiscal.Year
         #, target = Target.Value
         #, actual = Actual.Value
         ) %>% # A tibble:4,129 × 21
  group_by(ic, udn) %>%
  slice(which.max(as.Date(Formula.Start.Date))) # A tibble:3,993 × 21

cols <- c(names(udns)[names(udns) %in% names(indicators)]
          , "Formula")

# udns %>% 
#   mutate(across(is.list, .fn = ~ as.character(unlist(.))))

udns <- select(udns, all_of(cols))
```

## Join udn formulas
```{r}
list_udns <- function(x) {
  str_replace_all(x, "[()/+*]|100|Manual|NA", " ") %>% 
  str_extract_all(boundary("word"))
}

lapply(list_udns(udns$Formula[1:5]), FUN = function(x) paste(udns$ic[1:5], x))
list_udns(udns$Formula[1:5]) %>% length()
udns <- udns %>%
  mutate(uudn = paste(ic, udn, sep="_")
         , udn_formulas = map2_vec(Formula, ic,
                    ~ if_else(lengths(list_udns(.x)) > 0
                              , lapply(list_udns(.x)
                                       , function(x) paste(.y, x, sep="_"))
                              , list(NA_character_)))
         , .after=ic) %>%
  ungroup()

#udns$udn_formulas[1:5]
indicators <- indicators %>% 
  left_join(
    select(udns
           , -c(d_end, d_start, Disaggregate.Code, Disaggregate.Name))
    )

```



# Activities/ implementing mechanisms lookup
```{r}
# Activities/ Implemenitng mechanisms lookup
activities <- dat %>%
  distinct(ro , ou, a_code, a_name, ip
           , a_end, a_start
           , a_office, status, tags
           , Is.COVID, Is.Disaggregate.Blank, Is.FTF, Is.IPS, Is.Neither.PPR.PMP
           , Is.PMP, Is.PPR) %>%
  mutate(id = return_id(.), .before = everything())
```


# Countries
```{r}
ftf_target_countries <- data.frame(
  country = c("Bangladesh","Democratic Republic of the Congo",
              "Ethiopia","Ghana", "Guatemala","Honduras",
              "Kenya","Liberia", "Madagascar","Malawi",
              "Mali","Mozambique", "Nepal","Niger",
              "Nigeria","Rwanda","Senegal","Tanzania",
              "Uganda","Zambia"), ftf_target = TRUE)

ppp_countries <- read.csv("../ppp_countries.csv")

countries <-  dat %>% 
  distinct(country = str_to_title(Disaggregate.Country)) %>%
  filter(country != "") %>%
  mutate(id = rownames(.), .before = everything()) %>%
  left_join(ftf_target_countries) %>%
  left_join(ppp_countries, join_by(country == Disaggregate.Country))


```


# Offices
```{r}
# Offices
offices <- dat %>%
  distinct(m_code, m_office) %>%
  mutate(id = return_id(.), .before = everything())
```


# Values
```{r}
# Values
values <- dat %>% # 3,653,389 
   # indicator
  left_join(indicators) %>% rename(id_ind = id) %>% # 310,803
  # activity
  left_join(activities) %>% rename(id_ac = id) %>%
  # office
  left_join(offices,
            join_by(m_code, m_office)) %>%
  rename(id_off = id) %>%

  select(id_ind, id_ac, id_off, year, actual, target) %>%
  mutate(id = return_id(.), .before = everything())
```

```{r}

# unique_udns <- data.frame(indicator = "EG.3.2-27",
#                       udn = c(
#           # 3.7 = Non-debt
#           "3.5.1.2.1", "3.5.1.2.2", "3.5.1.2.3", "3.5.1.2.4", "3.5.1.2.5", # 3.5 = Type of financing accessed: Cash Debt
#           "3.5.2.2.1", "3.5.2.2.2", "3.5.2.2.3", "3.5.2.2.4", "3.5.2.2.5",
#           
#           "3.6.1.2.1", "3.6.1.2.2", "3.6.1.2.3", "3.6.1.2.4", "3.6.1.2.5",	 # 3.6 Type of financing accessed: In-Kind Debt
#           "3.6.2.2.1", "3.6.2.2.2", "3.6.2.2.3", "3.6.2.2.4", "3.6.2.2.5",
#           
#           "3.7.1.2.1", "3.7.1.2.2", "3.7.1.2.3", "3.7.1.2.4", "3.7.1.2.5", # 3.7 	Type of financing accessed: Non-Debt
#           	"3.7.2.2.1","3.7.2.2.2","3.7.2.2.3","3.7.2.2.4","3.7.2.2.5"  # Value Type of financing accessed: Non-Debt
#           ))
# 
# 
# 
# 	
# 	# filter_indicators("EG.3.2-27") %>% filter(Disaggregate.Data.Entry.Type =="Label") %>%
# 	#   left_join(values, by=join_by(id == id_ind)) %>% filter(if_any(c(actual, target), ~ !is.na(.)))
# 	#   filter(nchar(udn) == 3 & str_starts(udn, "3")) %>%
# 	#   select(udn, Disaggregate.Name) %>% distinct()
# 	# 


```

```{r}
ppp <- read.csv("../API_PA.NUS.PPP_DS2_en_csv_v2_5734723.csv", skip = 4) %>%
  select(-`Indicator.Name`,- `Indicator.Code`) %>%
  pivot_longer(-c(`Country.Name`, `Country.Code`), 
               names_to = "year", values_to = "ppp_multiplier") %>%
  mutate(year = as.integer(str_remove(year, "X"))) %>%
  filter(!is.na(ppp_multiplier))

prvt_pp <- read.csv("../API_PA.NUS.PRVT.PP_DS2_en_csv_v2_5734724.csv", skip = 4) %>%
  select(-`Indicator.Name`,- `Indicator.Code`) %>%
  pivot_longer(-c(`Country.Name`, `Country.Code`), 
               names_to = "year", values_to = "prvt_pp") %>%
  mutate(year = as.integer(str_remove(year, "X"))) %>%
  filter(!is.na(prvt_pp))

exch_rate <- read.csv("../API_PA.NUS.FCRF_DS2_en_csv_v2_5729637.csv", skip = 4) %>%
  select(-`Indicator.Name`,- `Indicator.Code`) %>%
  pivot_longer(-c(`Country.Name`, `Country.Code`), 
               names_to = "year", values_to = "exch_rate") %>%
  mutate(year = as.integer(str_remove(year, "X"))) %>%
  filter(!is.na(exch_rate))
```


# Write to files
```{r}
save(indicators, activities, countries, ppp, prvt_pp, exch_rate
     , ppp_countries, ftf_target_countries, offices, values, udns
     , file = "../database/extract/indicators_db.Rdata")
save(indicators, activities, countries, ppp, prvt_pp, exch_rate
     , ppp_countries, ftf_target_countries, offices, values, udns
     , file = "../disR/data/extract.Rdata")
```


